version: '3'

services:
  db:
    image: mysql
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password1

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m30s
      timeout: 10s
      retries: 3

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB=mysql
      - DB_PORT=3306
      - DB_PASSWORD=password1
      - SITE_ROOT=http://127.0.0.1:8000

    depends_on:
      - db
